### ISSUE TITLE
TravisCI and Coveralls integration

### ISSUE THREAD

**Issue by tdeekens** [sbstnmsch/mean6#2]
# Wät is in this

![Do no work](http://ddf912383141a8d7bbe4-e053e711fc85de3290f121ef0f0e3a1f.r87.cf1.rackcdn.com/automate-all-the-things.jpg)

TravisCI automagically runs tests for back- and frontend, coveralls reports on coverage.

## Todo

- [ ] Add TravisCI build hook
- [ ] Add Coveralls built hooks
- [ ] .travis.yml
- [ ] Add some dull dummy tests
